version: "3.8"

services:
  app:
    image: back-master:0.0.1
    build: .
    volumes:
      - .:/QRMenu
    ports:
      - "8001:8001"
    #container name: QRMenu_container
    command: python manage.py runserver 0.0.0.0:8001