version: "3.8"

services:
  app1:
    image: back-master:0.0.1
    build: .
    volumes:
      - ./app1:/app/db
      - ./app1:/app/images
    ports:
      - "8001:8000"
    container_name: app1
    command: ./runserver.sh app1
# 

  app2:
    image: back-master:0.0.1
    build: .
    volumes:
      - ./app2:/app/db
      - ./app2:/app/images
    ports:
      - "56847:8000"
    container_name: app2
    command: ./runserver.sh app2

  app3:
    image: back-master:0.0.1
    build: .
    volumes:
      - ./app3:/app/db
    ports:
      - "9476:8000"
    container_name: app3
    command: ./runserver.sh app3
