# Generated by Django 4.1.2 on 2022-10-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('gramms', models.IntegerField()),
                ('cals', models.IntegerField()),
            ],
        ),
    ]
