# Generated by Django 4.1.3 on 2022-12-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fonts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('font', models.FileField(upload_to='fonts/')),
            ],
        ),
        migrations.CreateModel(
            name='menuSections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default=None, max_length=350, null=True)),
                ('price', models.IntegerField()),
                ('gramms', models.IntegerField(blank=True, default=None, null=True)),
                ('calories', models.IntegerField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('section', models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='menu.menusections')),
            ],
        ),
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafename', models.CharField(default='cafe', max_length=50)),
                ('headertxt', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('bgheader', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('bgup', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('bgcenter', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('bgdown', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('bgpage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('bgend', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('fontcolor', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('style', models.BooleanField()),
                ('font', models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='menu.fonts')),
            ],
        ),
    ]
