# Generated by Django 4.1.3 on 2022-11-27 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menuSections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='cals',
        ),
        migrations.AddField(
            model_name='items',
            name='calories',
            field=models.IntegerField(blank=True, default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='items',
            name='gramms',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='items',
            name='section',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menusections'),
        ),
    ]
