# Generated by Django 4.1.3 on 2022-12-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='style',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fonts',
            name='font',
            field=models.FileField(upload_to='menu/static/fonts/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='section',
            field=models.ForeignKey(blank=True, default=9, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='menu.menusections'),
        ),
    ]
