# Generated by Django 4.1.3 on 2022-12-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_design_style_alter_fonts_font_and_more'),
        ('menu', '0002_fonts_fontfamily_alter_design_style_alter_fonts_font_and_more'),
    ]

    operations = [

    ]
