# Generated by Django 4.1.3 on 2022-11-27 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menusections_remove_items_cals_items_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='calories',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='gramms',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='section',
            field=models.ForeignKey(blank=True, default=-1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='menu.menusections'),
            preserve_default=False,
        ),
    ]
