# Generated by Django 4.1.3 on 2022-11-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_items_calories_alter_items_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=350, null=True),
        ),
    ]
