# Generated by Django 4.1.3 on 2022-12-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_merge_20221225_1609'),
    ]

    operations = [
    ]
