# Generated by Django 4.1.3 on 2022-12-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_items_image_alter_items_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('font', models.TextField(blank=True, default=None, max_length=350, null=True)),
                ('fontcolor', models.CharField(max_length=50)),
                ('style', models.BooleanField()),
            ],
        ),
    ]
