# Generated by Django 4.1.3 on 2022-12-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20221225_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menuSections',
            new_name='menuSection',
        ),
        migrations.RemoveField(
            model_name='items',
            name='section',
        ),
    ]
