# Generated by Django 4.1.3 on 2022-12-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_menusections_menusection_remove_items_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default=None, max_length=350, null=True)),
                ('price', models.IntegerField()),
                ('gramms', models.IntegerField(blank=True, default=None, null=True)),
                ('calories', models.IntegerField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('section', models.ForeignKey(blank=True, default=10, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='menu.menusection')),
            ],
        ),
        migrations.RenameModel(
            old_name='fonts',
            new_name='font',
        ),
        migrations.DeleteModel(
            name='items',
        ),
        migrations.RemoveField(
            model_name='design',
            name='font',
        ),
    ]
