# Generated by Django 4.1.3 on 2022-12-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='cafename',
            field=models.CharField(default='cafe', max_length=50),
        ),
        migrations.AlterField(
            model_name='design',
            name='fontcolor',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
