# Generated by Django 4.1.3 on 2022-12-25 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_item_rename_fonts_font_delete_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='font',
            field=models.ForeignKey(blank=True, default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='menu.font'),
            preserve_default=False,
        ),
    ]
