# Generated by Django 4.1.2 on 2023-03-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_design_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('a', 'Available'), ('u', 'Unavailable')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='font',
            name='font',
            field=models.FileField(blank=True, null=True, upload_to='menu/static/fonts/'),
        ),
    ]
