# Generated by Django 4.2.1 on 2023-06-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_item_status_alter_font_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='fontcolor',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
    ]
